Milestone 5: Friendships Version 1
AndresFMoya/RoR-Facebook_Clone pull request #7
Opened 2019-11-28 20:48 UTC by AndresFMoya

Good day TSEs.

Friendship model was created with associations and all requested features.

Unit and Integration Test were performed with RSpec.

Best!

2019-11-28 23:10 UTC, mosaaleb requested changes
## Well done @KerronKing @AndresFMoya :clap:

#### Most requirements are handled, yet there are some needs to be met before moving on.

- [x] sender send a friend request to receiver, sender shouldn't be able to send another request to receiver, receiver shouldn't also be able to send a request to sender. This ensures that if for any reason why we have bugs in the views, no duplicate records will enter our database and sabotage our data integrity.
We can achieve this by adding interchangeable validation to check if the [user_id, friend_id] or [friend_id, user_id] exist in the friendship table. [please take a look at this example](https://stackoverflow.com/questions/29123620/rails-validate-unique-friendship-relationships).


- [x] **`[OPTIONAL]`** Previous step adds model validations to friendships uniqueness. I would suggest to add interchangeable DB validations. You need to know first why DB validations are important [why](https://thoughtbot.com/blog/the-perils-of-uniqueness-validations). 
My previous code partner wrote an article on how to achieve [this](https://www.freecodecamp.org/news/how-to-set-unique-interchangeable-index-constraint-in-rails/).

- [x] We have some failed tests -- Let's fix them.

![Screenshot from 2019-11-29 01-06-08](https://user-images.githubusercontent.com/4246637/69834673-895ef800-1244-11ea-8573-f18deaf8aa11.png)

#### Text me on slack if you have any questions.

#### Please handle these requirements and submit a new code review.

##### Muhammad Ebeid

2019-11-28 23:10 UTC, mosaaleb commented on app/models/user.rb
> +  has_many :friendships
- [x] Let's add dependent destroy to both `friendships` and `inverse_friendships` associations.

2019-11-28 23:10 UTC, mosaaleb commented on app/models/user.rb
> +    inverse_friend_ids = 'SELECT user_id FROM friendships WHERE friend_id = :user_id'
- [x] Posts written by a user who requested my friendship, and not yet accepted shouldn't appear to my newsfeed page. We need to only include confirmed friendships for `inverse_friend_ids`

2019-11-29 16:29 UTC, AndresFMoya commented
Good day @mosaaleb. Thanks for your feedback. All requirements were met. Looking to hear your comments. New code review was asked.

Best!

2019-11-29 22:01 UTC, mosaaleb approved these changes
## Well done @AndresFMoya, @KerronKing 👏

#### All requirements are handled. Also, the UI is replica :sparkles:. 

#### You can merge :+1:

#### Good luck with the next milestones.

2019-11-29 22:55 UTC, merged